@startuml
title function [_XXX]
' scale 1000*500
autonumber 
!pragma teoz true
box "Internal Service" #LightBlue
participant data_stor as d_st
box "sub command"
participant proc_stor as p_st
end box
participant data_in as d_in
end box
participant data_out as d_out
participant function as fn
== up data ==



    
alt  l_02_dd2e od.d
    d_st -> d_in : l_02_dd2e od.d
        note right
        <code>
        for read
        </code>
        end note
    group My own label
    d_in -> d_st : l_02_dd2e od.d
    end
ref over d_st
od.d
end ref
else
        d_in <- d_st
        note right
        <code>
        for read
        </code>
        end note
end

opt
end

loop
end

break
end


== fn work ==

ref over d_in
stdin
end ref
d_in -> fn : fl_nm
note right
<code>
cat fl_nm
</code>
end note
ref over d_out
stdout
end ref
== ret data ==
ref over fn
epm full-upgrad
end ref

create wrappedRequest
fn -> wrappedRequest: new request()
p_st <-- d_st: response




@enduml
