@startmindmap

*:
ПРИНЯТЫЕ ОБОЗНАЧЕНИЯ И УСЛОВНОСТИ :

<file:> <path_to_file>
<nnn:> - номер строки в файле
указывается только значимый код 
в терминах псевдокода похожего на bash
source <path_to_file> влечет за собой 
раскрытие содержания <path_to_file> в 
правой секции соединенной с текущей секцией
;

*:

STL ВНУТРЕННИЕ УПРАВЛЯЮЩИЕ ФАЙЛЫ STL

. \~/.stl.d директория подключения STL библиотек


USER ВНЕШНИЕ УПРАВЛЯЮЩИЕ ФАЙЛЫ STL

1. \~/.is_bashrc_log 
    flag=$(cat \~/.is_bashrc_log) 
        if $flag=0 то вывод {source \~/.d/.rc.d/.st.rc.d/.st.rc} в stdout/err
        if $flag=1 то вывод {source \~/.d/.rc.d/.st.rc.d/.st.rc} в \~/bashrc.log



USER ВНЕШНИЕ ИНФОРМАЦИОННЫЕ ФАЙЛЫ STL

1. \~/bashrc.log log of {source \~/.d/.rc.d/.st.rc.d/.st.rc}

;

@endmindmap