@startmindmap
*:
ПРИНЯТЫЕ ОБОЗНАЧЕНИЯ И УСЛОВНОСТИ :

<file:> <path_to_file>
<nnn:> - номер строки в файле
указывается только значимый код 
в терминах псевдокода похожего на bash
source <path_to_file> влечет за собой 
раскрытие содержания <path_to_file> в 
правой секции соединенной с текущей секцией
;

*:
СОСТАВ ФАЙЛОВОЙ СИСТЕМЫ ПРОЕКТА
ВНУТРЕННИЕ УПРАВЛЯЮЩИЕ ФАЙЛЫ
USER ВНЕШНИЕ УПРАВЛЯЮЩИЕ ФАЙЛЫ
USER ВНЕШНИЕ ИНФОРМАЦИОННЫЕ ФАЙЛЫ STL
;


*:
file:\~/path

000: define fn() {}
000: fn 
000: source \~/path_s
;

**:define: fn() {
    any_act
}
;

**:exec: fn
;

***:any_act
;

**:source: \~/path_s
;

***:
file:\~/path_s

000: define fn() {}
000: fn 
000: source \~/path_s
;

@endmindmap