@startmindmap
'/home/st/.stl.d/stl.boot.d/stl.boot.flumen.d/_stl.boot.flumen.puml.cntx.d/__001.stdgm.puml



*:
file:\~/path

000: define fn() {}
000: fn 
000: source \~/path_s
N0
;































@endmindmap
